// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNjVq8kjjv9vDN4jfYAgBrMn3f8L11xj8',
    appId: '1:215336515707:web:6430db84363fa838f64ade',
    messagingSenderId: '215336515707',
    projectId: 'd0jp6ktd6o7qsb2uybihy618hb4aw2',
    authDomain: 'd0jp6ktd6o7qsb2uybihy618hb4aw2.firebaseapp.com',
    storageBucket: 'd0jp6ktd6o7qsb2uybihy618hb4aw2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Le1xpHRsSa-JEyVBH0FazU-BuMai91k',
    appId: '1:215336515707:android:e30ede983b61d90df64ade',
    messagingSenderId: '215336515707',
    projectId: 'd0jp6ktd6o7qsb2uybihy618hb4aw2',
    storageBucket: 'd0jp6ktd6o7qsb2uybihy618hb4aw2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALrH4Q96kLrnLEmKmColG9bMj4qRceLmI',
    appId: '1:215336515707:ios:e937e1b0b6b19bfaf64ade',
    messagingSenderId: '215336515707',
    projectId: 'd0jp6ktd6o7qsb2uybihy618hb4aw2',
    storageBucket: 'd0jp6ktd6o7qsb2uybihy618hb4aw2.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
